language: ruby
rvm:
  - 2.2.3
notifications:
  email:
    recipients:
      - ilya@artsymail.com
    on_success: never
    on_failure: always
before_script:
  - psql -c 'create database sup_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
